language: python
python:
  - "3.4"
  - "3.5.0b3"
  - "3.5-dev"
  - "nightly"

matrix:
  allow_failures:
    - python: "3.5-dev"

install:
  - "python setup.py install"
  - "pip install pyflakes"

script:
  - py.test
  - catimg --help
  - catimg --update --verbose
  - catimg > /dev/null
  - pyflakes catimg/**/!(__init__).py setup.py

sudo: false
