language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5.0b3"
  - "3.5-dev"
  - "nightly"

matrix:
  allow_failures:
    - python: "3.5.0b3"
    - python: "3.5-dev"
    - python: "nightly"

install: "pip install requests imgurpython 'iterm2-tools>=2.0'"

script:
  - py.test
  - catimg --help
  - catimg --verbose

sudo: false
