package:
  name: catimg
  version: "1.1"

source:
  fn: catimg-1.1.tar.gz
  url: https://pypi.python.org/packages/source/c/catimg/catimg-1.1.tar.gz
  md5: 5b5f7b3175a320e478a639e96e36a8a5
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - catimg = catimg:main
    #
    # Would create an entry point called catimg that calls catimg.main()

    - catimg = catimg.__main__:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - requests
    - imgurpython
    - iterm2-tools >=2.0

  run:
    - python
    - requests
    - imgurpython
    - iterm2-tools >=2.0

test:
  # Python imports
  imports:
    - catimg

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - catimg --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/asmeurer/catimg
  license: MIT
  summary: 'Print an image of a cat from Imgur to iTerm2.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
